// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQezzYmotPQ5YLZwEm06JAPfzZGKUW4fQ',
    appId: '1:1051295033097:web:6d516ee49321c67d2555d8',
    messagingSenderId: '1051295033097',
    projectId: 'closet-companion-clean',
    authDomain: 'closet-companion-clean.firebaseapp.com',
    storageBucket: 'closet-companion-clean.firebasestorage.app',
    measurementId: 'G-ELTQQHWX70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDCbHvVlv--AWOC2MlCbXdTVFdpc_BRZ0',
    appId: '1:1051295033097:android:c15b4077fa7a6b842555d8',
    messagingSenderId: '1051295033097',
    projectId: 'closet-companion-clean',
    storageBucket: 'closet-companion-clean.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo0dGdKbTMfuWXbiw2uQ_THVuEgZQ4iC0',
    appId: '1:1051295033097:ios:a1d3dace6641169c2555d8',
    messagingSenderId: '1051295033097',
    projectId: 'closet-companion-clean',
    storageBucket: 'closet-companion-clean.firebasestorage.app',
    iosBundleId: 'com.example.closetCompanionClean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo0dGdKbTMfuWXbiw2uQ_THVuEgZQ4iC0',
    appId: '1:1051295033097:ios:a1d3dace6641169c2555d8',
    messagingSenderId: '1051295033097',
    projectId: 'closet-companion-clean',
    storageBucket: 'closet-companion-clean.firebasestorage.app',
    iosBundleId: 'com.example.closetCompanionClean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQezzYmotPQ5YLZwEm06JAPfzZGKUW4fQ',
    appId: '1:1051295033097:web:efee33117821bcf82555d8',
    messagingSenderId: '1051295033097',
    projectId: 'closet-companion-clean',
    authDomain: 'closet-companion-clean.firebaseapp.com',
    storageBucket: 'closet-companion-clean.firebasestorage.app',
    measurementId: 'G-E0ZRYQV1J0',
  );
}
